version: "3"
networks:
  loki:
services:
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  grafana:
      image: grafana/grafana:latest
      user: "1000"
      volumes:
      - /home/serveradmin/docker_volumes/grafana:/var/lib/grafana
      ports:
        - "3953:3000"
      restart: unless-stopped
      networks:
        - loki
