server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: windows
  windows_events:
    use_incoming_timestamp: true
    bookmark_path: "./bookmark.xml"
    eventlog_name: "Security"
    xpath_query: '*'
    labels:
      job: windows
  pipeline_stages:
  - json:
      expressions:
        level: levelText
  - labels: 
      level:

#scrape_configs:
#- job_name: windows
#  windows_events:
#    use_incoming_timestamp: false
#    bookmark_path: "./bookmark.xml"
#    eventlog_name: "Application"
#    xpath_query: '*'
#    labels:
#      job: windows