services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    ports:
      - "8181:8181"
    expose:
      - 8181
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    command:
      [
        "influxdb3",
        "serve",
        "--node-id",
        "host01",
        "--object-store",
        "file",
        "--data-dir",
        "/var/lib/influxdb2",
      ]

  influxdb3-explorer:
    image: quay.io/influxdb/influxdb3-explorer:latest
    container_name: influxdb3-explorer
    ports:
      - "8888:8888"
    expose:
      - 8888
    depends_on:
      - influxdb

volumes:
  influxdb_data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/influxdb2
      o: bind
