global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    honor_labels: true
    static_configs:
      - targets: ["localhost:9090"]
  #- job_name: otel
    #metrics_path: /v1/
    #scheme: http
    #honor_labels: true
    #static_configs:
      #- targets: ["localhost:4317"]
      #- targets: ["localhost:4318"]
      #- targets: ["localhost:8888"]
      #- targets: ["localhost:8889"]