version: "3"

volumes:
  db_data:
    driver: local
  grafana_data:
    driver: local
  pgadmin_data:
    driver: local
  gitlab_config:
    driver: local
  gitlab_logs:
    driver: local
  gitlab_data:
    driver: local

services:
  zabbix-server:
    hostname: zabbix-server
    restart: unless-stopped
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    #podman pull zabbix/zabbix-server-pgsql:alpine-6.0-latest --tls-verify=false
    #${ZABBIX_VERSION}
    environment:
      - DB_SERVER_PORT=5432
      - DB_SERVER_HOST=postgresql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - ENABLE_TIMESCALEDB=true
      - ZBX_STARTREPORTWRITERS=2
      - ZBX_WEBSERVICEURL=http://zabbix-reports:10053/report
    #volumes:
      #- ./zabbix/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    depends_on:
      - postgresql

  zabbix-frontend:
    hostname: zabbix-frontend
    restart: unless-stopped
    image: zabbix/zabbix-web-apache-pgsql:alpine-6.0-latest
    #podman pull zabbix/zabbix-web-apache-pgsql:alpine-6.0-latest --tls-verify=false
    #${ZABBIX_VERSION}
    environment:
      - DB_SERVER_PORT=5432
      - DB_SERVER_HOST=postgresql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_NAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      #- ./zabbix/etc/ssl/apache2:/etc/ssl/apache2:ro
      - ../.podman_volumes/zabbix/etc/timezone:/etc/timezone:ro
      - ../.podman_volumes/zabbix/etc/localtime:/etc/localtime:ro
      - ../.podman_volumes/zabbix/etc/ssl/apache2:/etc/ssl/apache2:ro

    depends_on:
      - postgresql
      - zabbix-server

  postgresql:
    hostname: postgresql
    restart: unless-stopped
    image: timescale/timescaledb:2.8.1-pg14-oss
    #podman pull timescale/timescaledb:2.8.1-pg14-oss --tls-verify=false
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - TS_TUNE_MEMORY=4GB
      - TS_TUNE_NUM_CPUS=4
    volumes:
      - ../.podman_volumes/zabbix/db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=1000"]

  zabbix-agent:
    hostname: zabbix-agent
    restart: unless-stopped
    image: zabbix/zabbix-agent:alpine-6.0-latest
    #podman pull zabbix/zabbix-agent:alpine-6.0-latest --tls-verify=false
    #${ZABBIX_VERSION}
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_DEBUGLEVEL=4
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_SERVER_HOST=zabbix-server
    volumes:
      - ../.podman_volumes/zabbix/etc/timezone:/etc/timezone:ro
      - ../.podman_volumes/zabbix/etc/localtime:/etc/localtime:ro
      - ../.podman_volumes/zabbix/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ../.podman_volumes/zabbix/frontend_hacks:/usr/share/zabbix/local/
    depends_on:
      - zabbix-server

  zabbix-reports:
    hostname: zabbix-reports
    restart: unless-stopped
    image: zabbix/zabbix-web-service:alpine-6.0-latest
    #podman pull zabbix/zabbix-web-service:alpine-6.0-latest --tls-verify=false
    #${ZABBIX_VERSION}
    environment:
      - ZBX_ALLOWEDIP=zabbix-server,zabbix-frontend
      - ZBX_DEBUGLEVEL=4
    cap_add:
      - SYS_ADMIN
    depends_on:
      - zabbix-server
      - zabbix-frontend
  
  pgadmin:
    hostname: pgadmin
    restart: unless-stopped
    image: thajeztah/pgadmin4
    #podman pull thajeztah/pgadmin4:latest --tls-verify=false
    volumes:
      - pgadmin_data:/pgadmin
    depends_on:
      - postgresql

  #mailhog:
    #hostname: mailhog
    #restart: unless-stopped
    #image: mailhog/mailhog:v1.0.0
    #environment:
    #  - MH_HOSTNAME=mailhog

  zabbix-provisioning:
    hostname: zabbix-provisioning
    image: python:3.8.5-alpine3.12
    #podman pull python:3.8.5-alpine3.12 --tls-verify=false
    command: ["python", "/tmp/provisioning.py"]
    volumes:
      - ./provisioning.py:/tmp/provisioning.py:ro
    depends_on:
      - zabbix-frontend

  # gitlab:
  #   image: gitlab/gitlab-ce:latest
  #   restart: unless-stopped
  #   hostname: gitlab
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'http://gitlab:8929'
  #       gitlab_rails['gitlab_shell_ssh_port'] = 2224
  #       gitlab_rails['initial_root_password'] = 'rootpassword'
  #   volumes:
  #     - gitlab_config:/etc/gitlab
  #     - gitlab_logs:/var/log/gitlab
  #     - gitlab_data:/var/opt/gitlab

  # drawio:
  #   image: jgraph/drawio
  #   hostname: drawio
  #   restart: unless-stopped
  #   environment:
  #     PUBLIC_DNS: drawio
  #     ORGANISATION_UNIT: zabbixlab
  #     ORGANISATION: zabbixlab
  #     CITY: zabbixlab
  #     STATE: zabbixlab
  #     COUNTRY_CODE: BR
  #   environment:
  #     - DRAWIO_BASE_URL=http://drawio
  #     - DRAWIO_GITLAB_URL=http://gitlab:8929
  #     - DRAWIO_GITLAB_ID=e8ee248fa759f0f68b8595317e9bedb585f282491464f71d9b2ebda89dd49218
  #     - DRAWIO_CSP_HEADER=default-src \'self\'; script-src \'self\' \'unsafe-inline\'; connect-src \'self\' http://gitlab; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\';
  #   depends_on:
  #     - gitlab