# Use root/example as user/password credentials
version: "3.1"
#docker pull timescale/timescaledb:latest-pg14
services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    volumes:
      - ../.podman_volumes/timescaledb:/home/postgres/pgdata/data
    environment:
      POSTGRES_PASSWORD: TechOps!
    ports:
      - 5432:5432
    networks:
      - timescale
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - timescale

networks:
  timescale:
