#podman-compose up -d --force-recreate
version: "2.1"
networks:
  alloy:
services:
  alloy:
    image: alloy:latest
    ports:
      - "12347:12345"
      #- "12348:12348"
      #- "6832:6832"
      #- "55679:55679"
    volumes:
      #- "./config.pfsense.alloy:/etc/alloy/config.alloy"
      #- "./data/pfsense.log:/tmp/syslog.log"
      #- "./config.json.alloy:/etc/alloy/config.alloy"
      #- "./data/ngnix.log:/tmp/ngnix.log"
      #- "./data/shawn.maddock.json:/tmp/shawn.maddock.log"
      #- "./data/videos.log:/tmp/videos.log"
      - "./data/grafana.log:/tmp/grafana.log"

      #- "./config.jazz.alloy:/etc/alloy/config.alloy"
      #- "./data/jazz.log:/tmp/jazz.log"
      #- "./configs/config.windowsevents.alloy:/etc/alloy/config.alloy"
      #- "./configs/shawn.maddock.alloy:/etc/alloy/config.alloy"
      #- "./configs/shawn.match.alloy:/etc/alloy/config.alloy"
      #- "./configs/config.regex.alloy:/etc/alloy/config.alloy"
      #- "./configs/config.hack3rcon.alloy:/etc/alloy/config.alloy"
      #- "./configs/config.videos.alloy:/etc/alloy/config.alloy"
      - "./configs/config.grafana.alloy:/etc/alloy/config.alloy"
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--storage.path=/var/lib/alloy/data",
        "--stability.level=public-preview",
        "/etc/alloy/config.alloy",
      ]
    networks:
      - alloy
  # The Loki service stores logs sent to it, and takes queries from Grafana
  # to visualise those logs.
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - alloy
