#podman-compose up -d --force-recreate
version: "2.1"
networks:
  alloy:
services:
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12347:12345"
      #- "12348:12348"
      #- "6832:6832"
      #- "55679:55679"
    volumes:
      - "./config.pfsense.alloy:/etc/alloy/config.alloy"
      - "./data/pfsense.log:/tmp/syslog.log"
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--storage.path=/var/lib/alloy/data",
        "--stability.level=public-preview",
        "/etc/alloy/config.alloy",
      ]
    networks:
      - alloy
  # The Loki service stores logs sent to it, and takes queries from Grafana
  # to visualise those logs.
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - alloy
