#docker run --name cloudbeaver -d --restart unless-stopped -p 8978:8978 -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:latest
version: "3.1"

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver
    restart: unless-stopped
    ports:
      - 8978:8978
    volumes:
      - "../.podman_volumes/dbeaver/workspace:/opt/cloudbeaver/workspace:rw"
