# Use terraform/example user/password credentials
version: "3.1"

services:
  #docker pull hashicorp/terraform
  terraform:
    image: hashicorp/terraform
    restart: always
    volumes:
      - ../.podman/terraform:/var/lib/terraformql/data
    networks:
      - terraform-net

networks:
  terraform-net:
