# Use root/example as user/password credentials
version: "3.1"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    ports:
      - 8080:80
    volumes:
      #- "./nginx.conf:/etc/nginx/nginx.conf:ro"
      #- ./nginx.conf:/etc/nginx/sites-enabled/grafana.conf:ro
      #- ./default.conf:/etc/nginx/conf.d/default.conf
      - "./default.conf:/etc/nginx/nginx.conf"
      - "./htpasswd:/etc/nginx/htpasswd"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    volumes:
      - ./defaults.ini:/usr/share/grafana/conf/defaults.ini:ro
    ports:
      - 5000:3000
