version: "3"

networks:
  internal:
    driver: bridge

services:
  zabbix_mysql:
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=
    image: zabbix/zabbix-server-mysql
    ports:
      - "3306:3306"
    networks:
      - internal
