version: "3"
networks:
  loki:
services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      #- ../.podman_volumes/promtail/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./log/sql.log:/var/log/sql.log

    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
