version: "3"

services:
  mosquitto:
    #image: eclipse-mosquitto:latest
    image: hivemq/hivemq4:latest
    container_name: hivemq
    #    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
      - "8080:8080"
    networks:
      - iot
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  #  influxdb:
  #    image: influxdb:latest
  #    container_name: influxdb
  ##    restart: always
  #    ports:
  #      - "8086:8086"
  #    networks:
  #      - iot
  #    volumes:
  #      - influxdb-data:/var/lib/influxdb2
  #      - influxdb-config:/etc/influxdb2
  #    environment:
  #      - DOCKER_INFLUXDB_INIT_MODE=setup
  #      - DOCKER_INFLUXDB_INIT_USERNAME=user
  #      - DOCKER_INFLUXDB_INIT_PASSWORD=password1234
  #      - DOCKER_INFLUXDB_INIT_ORG=roboteek
  #      - DOCKER_INFLUXDB_INIT_BUCKET=donnees_robot
  #      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=4eYvsu8wZCJ6tKuE2sxvFHkvYFwSMVK0011hEEiojvejzpSaij86vYQomN_12au6eK-2MZ6Knr-Sax201y70w==

  #  telegraf:
  #    image: telegraf:latest
  #    container_name: telegraf
  ##    restart: always
  #    volumes:
  #      - ./telegraf_live.conf:/etc/telegraf/telegraf.conf:ro
  #    depends_on:
  #      - mosquitto
  ##      - influxdb
  #    networks:
  #      - iot

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    #    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      #      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_API_KEY_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
#      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
#    depends_on:
#      - influxdb

networks:
  iot:

volumes:
  grafana-data:
#  influxdb-data:
#  influxdb-config:
