version: "2"

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:9.5.5
    container_name: grafana
    user: "1000"
    ports:
      - "3955:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ../.podman_volumes/grafana:/var/lib/grafana
      - ../.podman_volumes/grafana/etc/grafana:/etc/grafana
      - ../.podman_volumes/grafana/plugins:/var/lib/grafana/plugins
    networks:
      - grafana
    restart: unless-stopped
