version: "3"
networks:
  grafanet:
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - grafanet

  #prometheus:
  #  image: prom/prometheus
  #  volumes:
  #    - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  #  ports:
  #    - "9090:9090"
  #  restart: unless-stopped
  #  networks:
  #    - grafanet
  mimir:
    image: grafana/mimir:latest
    volumes:
      - ./mimir-config.yml:/etc/mimir/mimir-config.yml
    command: -config.file=/etc/mimir/mimir-config.yml
    ports:
      - "9009:9009"
    restart: unless-stopped
    networks:
      - grafanet
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - ../.podman_volumes/grafana:/var/lib/grafana
    ports:
      - "3954:3000"
    restart: unless-stopped
    networks:
      - grafanet
