# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    restart: always
    environment:
      ACCEPT_EULAY: Y
      MSSQL_SA_PASSWORD: L1f31nP3ac3@L@st
    ports:
      - 1400:1433
    networks:
      - mssql-net

networks:
  mssql-net:
