version: '3.6'
services:
  influxdb:
      image: influxdb:1.8
      #image: influxdb:latest
      container_name: influxdb
      restart: always
      environment:
        - INFLUXDB_DB=influx
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=TechOps!
      ports:
        - '8086:8086'
      #volumes:
      #  - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
volumes:
  grafana_data: {}
  influxdb_data: {}        