version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ../.podman_volumes/promtail:/var/log
      - ./promtail-local-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki
    depends_on:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - "3953:3000"
    networks:
      - loki

#volumes:
#  promtail:
#  sock: