version: "3"
networks:
  loki:
services:
  grafana:
    image: grafana/grafana:latest
    #user: "1000"
    volumes:
      #- ../.podman_volumes/grafana:/var/lib/grafana
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "9300:3000"
    restart: unless-stopped
    networks:
      - loki

  loki:
    image: grafana/loki:2.8.0
    volumes:
      - ./config/loki:/mnt/config
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log:/var/log
      - ./config/promtail:/mnt/config
      - ./log/sql.log:/var/log/sql.log
      #- /var/run/docker.sock:/var/run/docker.sock

    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: --config.file=/mnt/config/promtail-config.yaml
    networks:
      - loki
