# Use root/example as user/password credentials
version: "3.1"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    #volumes:
    #  - ./conf_grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
    ports:
      - 5000:3000
