# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: trinodb/trino
    restart: always
    ports:
      - 8080:8080
    networks:
      - trino-net

networks:
  trino-net:
