version: '2'

services:
  grafana:
      image:  docker.io/grafana/grafana:latest
      container_name: grafana
      environment:
        - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
        - GF_PATHS_DATA=/var/lib/grafana
        - GF_PATHS_HOME=/usr/share/grafana
        - GF_RENDERING_SERVER_URL=http://renderer:8081/render
        - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
        - GF_LOG_FILTERS=rendering:debug
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_AUTH_ANONYMOUS_ENABLED=true        
      ports:
        - "3555:3000"
      volumes:
        - ./defaults.ini:/etc/grafana/grafana.ini
        - ../.podman_volumes/grafana:/var/lib/grafana
        - ../.podman_volumes/grafana/etc/grafana:/etc/grafana
      restart: unless-stopped

  renderer:
    image:  grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - "8081:8081"
    restart: unless-stopped
