version: "3"
services:
  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_CONTENT_SECURITY_POLICY=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PLUGINS_PREINSTALL=volkovlabs-echarts-panel
    volumes:
      - ./provisioning/datasources/001-datasources.yaml:/etc/grafana/provisioning/datasources/001-testdata.yaml
      #- ./provisioning/plugins/001-volkov-labs.business-chart.yaml:/etc/grafana/provisioning/plugins/volkov-labs.business-chart.yaml
      - ./provisioning/dashboards/002-dashboards.yaml:/etc/grafana/provisioning/dashboards/002-muzungi.yaml
      - ./provisioning/dashboards/Muzungi.json:/etc/grafana/dashboards/Mock Dashboard.json
      - ./provisioning/dashboards/airline-seats.json:/etc/grafana/dashboards/airline-seats.json
      - ./provisioning/img/flight-seats.svg:/usr/share/grafana/public/img/flight-seats.svg
    ports:
      - "3900:3000"
