version: "3"
services:
  grafana:
    #image: grafana/grafana:latest
    image: grafana/grafana:10.1.5
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - "3955:3000"
