version: '3.6'
services:
  influxdb:
      image: influxdb:1.8
      #image: influxdb:latest
      container_name: influxdb
      restart: always
<<<<<<< HEAD
      environment:
        - INFLUXDB_DB=influx
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=TechOps!
      ports:
        - '8086:8086'
      #volumes:
      #  - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
=======
      #environment:
      #  - INFLUXDB_DB=influx
      #  - INFLUXDB_ADMIN_USER=admin
      #  - INFLUXDB_ADMIN_PASSWORD=TechOps!
      ports:
        - '8086:8086'
      volumes:
        - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
>>>>>>> 0291f04b7301dbe09a72c1acfbf79523e10ffb99
volumes:
  grafana_data: {}
  influxdb_data: {}        