version: "3"
networks:
  loki:
services:
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail:
    image: grafana/promtail:latest
    volumes:
      #- ../.podman_volumes/promtail/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./log/sql.log:/var/log/sql.log

    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:9.5.5
    volumes:
      - ../.podman_volumes/grafana:/var/lib/grafana
    ports:
      - "3010:3000"
    restart: unless-stopped
    networks:
      - loki
