version: "3.3"
services:
  postgres:
    image: debezium/example-postgres:1.9
    #image: example-postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
