# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - ../.podman_volumes/cassandra:/var/lib/cassandra
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  cassandra-net: