version: "3.8"

#node --require /mnt/c/myapps/apis4grafana/instrumentation.js server.js
#OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 BEYLA_OTEL_INSECURE_SKIP_VERIFY=true BEYLA_PRINT_TRACES=true BEYLA_OPEN_PORT=4700 sudo -E beyla --config=beyla-config.yaml
services:
  beyla:
    image: grafana/beyla:latest
    pid: service:nodejs"
    # If using the above capability fails to instrument your service, remove it
    # and uncomment the line below
    privileged: true
    environment:
      BEYLA_OTEL_INSECURE_SKIP_VERIFY: true
      BEYLA_PRINT_TRACES: true
      BEYLA_OPEN_PORT: 5000
      #BEYLA_PROMETHEUS_PORT: 9090
      BEYLA_OTEL_INSECURE_SKIP_VERIFY: false
      #OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost"
      #OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ""
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4318"
      #OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      #4317 grpc
      #4318 http
      #OTEL_EXPORTER_OTLP_PROTOCOL: http/json
