# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "6543:5432"    
    environment:
      POSTGRES_PASSWORD: TechOps!

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080