# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:
    volumes:
      - ../.podman_volumes/postgresql/data:/var/lib/postgresql/data
    ports:
      - 6543:5432
    networks:
      - postgres-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-net

volumes:
  db:
    driver: local

networks:
  postgres-net:
