version: '2'

services:
  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - 3000:3000
    user: '104'
    volumeMounts:
      - mountPath: /etc/grafana/grafana.ini:Z
        name: grafana-config
      - mountPath: /var/lib/grafana:Z
        name: grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  networks:
      - resolute

networks:
  resolute:
    external:
      name: resolute      
volumes:
  prom_data: