# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 
    ports:
      - "6543:5432"
    #extra_hosts:
    #  - "host.docker.internal:127.0.0.1"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8068:8080